export type IFoodType = "VEG" | "NON_VEG";

export const FOOD_TYPE: Record<IFoodType, IFoodType> = {
  VEG: "VEG",
  NON_VEG: "NON_VEG",
};

export const STATIC_CONTENT_KEYS = {
  HERO_SECTION: "HERO_SECTION",
  FULL_PIZZA_SECTION: "FULL_PIZZA_SECTION",
  CHEF_SECTION: "CHEF_SECTION",
  TESTIMONIAL_SECTION: "TESTIMONIAL_SECTION",

  APPLICATION_CONFIG: "APPLICATION_CONFIG",

  // menu page
  MENU_PAGE_HERO_SECTION: "MENU_PAGE_HERO_SECTION",

  // contact page
  CONTACT_PAGE_HERO_SECTION: "CONTACT_PAGE_HERO_SECTION",

  // about page
  ABOUT_PAGE_HERO_SECTION: "ABOUT_PAGE_HERO_SECTION",
};
