export type IFoodType = "VEG" | "NON_VEG";

export const FOOD_TYPE: Record<IFoodType, IFoodType> = {
  VEG: "VEG",
  NON_VEG: "NON_VEG",
};

export const ROLES = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  USER: "USER",
};

export const STATIC_CONTENT_KEYS = {
  //home page
  HERO_SECTION: "HERO_SECTION",
  MENU_GLIMPSE_SECTION: "MENU_GLIMPSE_SECTION",
  FULL_PIZZA_SECTION: "FULL_PIZZA_SECTION",
  CHEF_SECTION: "CHEF_SECTION",
  TESTIMONIAL_SECTION: "TESTIMONIAL_SECTION",

  // application config
  APPLICATION_CONFIG: "APPLICATION_CONFIG",

  // menu page
  MENU_PAGE_HERO_SECTION: "MENU_PAGE_HERO_SECTION",

  // contact page
  CONTACT_PAGE_HERO_SECTION: "CONTACT_PAGE_HERO_SECTION",

  // about page
  ABOUT_PAGE_HERO_SECTION: "ABOUT_PAGE_HERO_SECTION",
  ABOUT_PAGE_PIZZA_SECTION: "ABOUT_PAGE_PIZZA_SECTION",
  ABOUT_PAGE_STATS_SECTION: "ABOUT_PAGE_STATS_SECTION",
  ABOUT_PAGE_CAROUSEL_SECTION: "ABOUT_PAGE_CAROUSEL_SECTION",

  //blog page
  BLOG_PAGE_HERO_SECTION: "BLOG_PAGE_HERO_SECTION",
};
