import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Trade_Winds } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const tradeWinds = Trade_Winds({
  subsets: ["latin"],
  weight: "400", // Trade Winds has only 400
  display: "swap",
  variable: "--font-trade-winds",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${tradeWinds.variable} antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
