// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginAuthDto = {
    /**
     * The email of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
};

export type RegisterAuthDto = {
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The phone number of the user
     */
    phone: string;
};

export type VerifyAccountAuthDto = {
    /**
     * The email of the user
     */
    email: string;
    /**
     * The OTP from the email sent to the user
     */
    otp: string;
};

export type InviteUserDto = {
    /**
     * The name of the user
     */
    name: string;
    /**
     * The email of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
    /**
     * The phone number of the user
     */
    phone: string;
    /**
     * The role of the user
     */
    role: 'USER' | 'ADMIN';
    /**
     * The status of the user
     */
    status: 'ACTIVE' | 'INACTIVE' | 'INVITED' | 'BANNED';
};

export type CreateCategoryDto = {
    /**
     * The name of the category
     */
    name: string;
};

export type BaseCategoryResponseDto = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type ProductResponseDto = {
    id: string;
    name: string;
    description: string;
    price: string;
    crossedPrice: string | null;
    categoryId: string;
    category: BaseCategoryResponseDto;
    mainImageId: {
        [key: string]: unknown;
    } | null;
    type: string;
    visible: boolean;
    isDeleted: boolean;
    createdAt: string;
    updatedAt: string;
};

export type CategoryResponseDto = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    products: Array<ProductResponseDto>;
};

export type CreateProductDto = {
    /**
     * The name of the product
     */
    name: string;
    /**
     * The description of the product
     */
    description: string;
    /**
     * The price of the product
     */
    price: number;
    /**
     * The crossed price of the product
     */
    crossedPrice?: number;
    /**
     * The image file to upload
     */
    image?: Blob | File;
    /**
     * The type of the product
     */
    type: string;
    /**
     * The category ID of the product
     */
    categoryId?: string;
    /**
     * Whether the product is visible to customers
     */
    visible?: boolean;
};

export type UpdateProductDto = {
    /**
     * The name of the product
     */
    name?: string;
    /**
     * The description of the product
     */
    description?: string;
    /**
     * The price of the product
     */
    price?: number;
    /**
     * The crossed price of the product
     */
    crossedPrice?: number;
    /**
     * The image file to upload
     */
    image?: Blob | File;
    /**
     * The type of the product
     */
    type?: string;
    /**
     * The category ID of the product
     */
    categoryId?: string;
    /**
     * Whether the product is visible to customers
     */
    visible?: boolean;
};

export type CreateContactDto = {
    /**
     * The name of the contact
     */
    name: string;
    /**
     * The email of the contact
     */
    email: string;
    /**
     * The phone number of the contact
     */
    phone: string;
    /**
     * The message from the contact
     */
    message: string;
};

export type UpdateContactDto = {
    /**
     * The name of the contact
     */
    name?: string;
    /**
     * The email of the contact
     */
    email?: string;
    /**
     * The phone number of the contact
     */
    phone?: string;
    /**
     * The message from the contact
     */
    message?: string;
};

export type UploadAssetDto = {
    /**
     * The image file to upload
     */
    file: Blob | File;
};

export type CreateAssetDto = {
    /**
     * The URL of the asset
     */
    url: string;
    /**
     * The public ID of the asset
     */
    publicId: string;
    /**
     * The type of the asset
     */
    type: 'IMAGE' | 'VIDEO' | 'DOCUMENT';
    /**
     * Additional metadata for the asset
     */
    metadata: {
        [key: string]: unknown;
    };
};

export type CreateOrderDto = {
    quantity: number;
    productId: string;
};

export type UpdateOrderDto = {
    quantity?: number;
    productId?: string;
};

export type CreateStaticContentDto = {
    [key: string]: unknown;
};

export type UpdateStaticContentDto = {
    [key: string]: unknown;
};

export type CreateTestimonialDto = {
    /**
     * The image file to upload
     */
    image?: Blob | File;
    /**
     * Name of the person giving the testimonial
     */
    name: string;
    /**
     * Designation of the person giving the testimonial
     */
    designation: string;
    isVisible: boolean;
    /**
     * Title of the testimonial
     */
    title: string;
    /**
     * Content of the testimonial
     */
    testimonial: string;
    /**
     * ID of the asset associated with the testimonial
     */
    assetId?: string;
};

export type TestimonialResponseDto = {
    readonly id: string;
    readonly name: string;
    readonly designation: string;
    readonly title: string;
    readonly testimonial: string;
    readonly isVisible: boolean;
    readonly assetId: string;
    readonly Asset: {
        [key: string]: unknown;
    };
};

export type UpdateTestimonialDto = {
    /**
     * The image file to upload
     */
    image?: Blob | File;
    /**
     * Name of the person giving the testimonial
     */
    name?: string;
    /**
     * Designation of the person giving the testimonial
     */
    designation?: string;
    isVisible?: boolean;
    /**
     * Title of the testimonial
     */
    title?: string;
    /**
     * Content of the testimonial
     */
    testimonial?: string;
    /**
     * ID of the asset associated with the testimonial
     */
    assetId?: string;
};

export type CreateOperationLogDto = {
    [key: string]: unknown;
};

export type UpdateOperationLogDto = {
    [key: string]: unknown;
};

export type CreateBlogDto = {
    [key: string]: unknown;
};

export type UpdateBlogDto = {
    [key: string]: unknown;
};

export type CreateStaticContentDtoWritable = {
    [key: string]: unknown;
};

export type UpdateStaticContentDtoWritable = {
    [key: string]: unknown;
};

export type CreateOperationLogDtoWritable = {
    [key: string]: unknown;
};

export type UpdateOperationLogDtoWritable = {
    [key: string]: unknown;
};

export type CreateBlogDtoWritable = {
    [key: string]: unknown;
};

export type UpdateBlogDtoWritable = {
    [key: string]: unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginAuthDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterAuthDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: unknown;
};

export type AuthControllerVerifyAccountData = {
    body: VerifyAccountAuthDto;
    path?: never;
    query?: never;
    url: '/api/auth/verify-account';
};

export type AuthControllerVerifyAccountResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    200: unknown;
};

export type UserControllerFindUserByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/get-me';
};

export type UserControllerFindUserByIdResponses = {
    200: unknown;
};

export type UserControllerInviteUserData = {
    body: InviteUserDto;
    path?: never;
    query?: never;
    url: '/api/user/invite-user';
};

export type UserControllerInviteUserResponses = {
    201: unknown;
};

export type UserControllerGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/all';
};

export type UserControllerGetAllUsersResponses = {
    200: unknown;
};

export type CategoryControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/category';
};

export type CategoryControllerFindAllResponses = {
    /**
     * List of categories with products
     */
    200: Array<CategoryResponseDto>;
};

export type CategoryControllerFindAllResponse = CategoryControllerFindAllResponses[keyof CategoryControllerFindAllResponses];

export type CategoryControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/api/category';
};

export type CategoryControllerCreateResponses = {
    201: unknown;
};

export type CategoryControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/category/{id}';
};

export type CategoryControllerFindOneResponses = {
    200: unknown;
};

export type CategoryControllerUpdateData = {
    body: CreateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/category/{id}';
};

export type CategoryControllerUpdateResponses = {
    200: unknown;
};

export type ProductControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type ProductControllerFindAllResponses = {
    /**
     * List of visible products for users
     */
    200: Array<ProductResponseDto>;
};

export type ProductControllerFindAllResponse = ProductControllerFindAllResponses[keyof ProductControllerFindAllResponses];

export type ProductControllerCreateData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/api/product';
};

export type ProductControllerCreateResponses = {
    201: unknown;
};

export type ProductControllerFindAllAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/product/admin';
};

export type ProductControllerFindAllAdminResponses = {
    /**
     * List of all products for admin
     */
    200: Array<ProductResponseDto>;
};

export type ProductControllerFindAllAdminResponse = ProductControllerFindAllAdminResponses[keyof ProductControllerFindAllAdminResponses];

export type ProductControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/product/{id}';
};

export type ProductControllerRemoveResponses = {
    200: unknown;
};

export type ProductControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/product/{id}';
};

export type ProductControllerFindOneResponses = {
    /**
     * Product details
     */
    200: ProductResponseDto;
};

export type ProductControllerFindOneResponse = ProductControllerFindOneResponses[keyof ProductControllerFindOneResponses];

export type ProductControllerUpdateData = {
    body: UpdateProductDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/product/{id}';
};

export type ProductControllerUpdateResponses = {
    200: unknown;
};

export type ContactControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/contact';
};

export type ContactControllerFindAllResponses = {
    200: unknown;
};

export type ContactControllerCreateData = {
    body: CreateContactDto;
    path?: never;
    query?: never;
    url: '/api/contact';
};

export type ContactControllerCreateResponses = {
    201: unknown;
};

export type ContactControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/contact/{id}';
};

export type ContactControllerRemoveResponses = {
    200: unknown;
};

export type ContactControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/contact/{id}';
};

export type ContactControllerFindOneResponses = {
    200: unknown;
};

export type ContactControllerUpdateData = {
    body: UpdateContactDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/contact/{id}';
};

export type ContactControllerUpdateResponses = {
    200: unknown;
};

export type AssetsControllerUploadData = {
    body: UploadAssetDto;
    path?: never;
    query?: never;
    url: '/api/assets/upload';
};

export type AssetsControllerUploadResponses = {
    201: unknown;
};

export type AssetsControllerCreateData = {
    body: CreateAssetDto;
    path?: never;
    query?: never;
    url: '/api/assets/create';
};

export type AssetsControllerCreateResponses = {
    201: unknown;
};

export type AssetsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/assets';
};

export type AssetsControllerFindAllResponses = {
    200: unknown;
};

export type StatsControllerGetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stats/dashboard';
};

export type StatsControllerGetDashboardStatsResponses = {
    200: unknown;
};

export type OrderControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/order';
};

export type OrderControllerFindAllResponses = {
    200: unknown;
};

export type OrderControllerCreateData = {
    body: CreateOrderDto;
    path?: never;
    query?: never;
    url: '/api/order';
};

export type OrderControllerCreateResponses = {
    201: unknown;
};

export type OrderControllerGetAllOrderGroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/order/order-group';
};

export type OrderControllerGetAllOrderGroupResponses = {
    200: unknown;
};

export type OrderControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/order/{id}';
};

export type OrderControllerRemoveResponses = {
    200: unknown;
};

export type OrderControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/order/{id}';
};

export type OrderControllerFindOneResponses = {
    200: unknown;
};

export type OrderControllerUpdateData = {
    body: UpdateOrderDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/order/{id}';
};

export type OrderControllerUpdateResponses = {
    200: unknown;
};

export type StaticContentControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/static-content';
};

export type StaticContentControllerFindAllResponses = {
    200: unknown;
};

export type StaticContentControllerCreateData = {
    body: CreateStaticContentDtoWritable;
    path?: never;
    query?: never;
    url: '/api/static-content';
};

export type StaticContentControllerCreateResponses = {
    201: unknown;
};

export type StaticContentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/static-content/{id}';
};

export type StaticContentControllerRemoveResponses = {
    200: unknown;
};

export type StaticContentControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/static-content/{id}';
};

export type StaticContentControllerFindOneResponses = {
    200: unknown;
};

export type StaticContentControllerUpdateWithKeyData = {
    body: UpdateStaticContentDtoWritable;
    path: {
        key: string;
    };
    query?: never;
    url: '/api/static-content/{key}';
};

export type StaticContentControllerUpdateWithKeyResponses = {
    200: unknown;
};

export type TestimonialControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/testimonial';
};

export type TestimonialControllerFindAllResponses = {
    /**
     * List of all testimonials
     */
    200: Array<TestimonialResponseDto>;
};

export type TestimonialControllerFindAllResponse = TestimonialControllerFindAllResponses[keyof TestimonialControllerFindAllResponses];

export type TestimonialControllerCreateData = {
    body: CreateTestimonialDto;
    path?: never;
    query?: never;
    url: '/api/testimonial';
};

export type TestimonialControllerCreateResponses = {
    201: unknown;
};

export type TestimonialControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/testimonial/{id}';
};

export type TestimonialControllerRemoveResponses = {
    200: unknown;
};

export type TestimonialControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/testimonial/{id}';
};

export type TestimonialControllerFindOneResponses = {
    200: unknown;
};

export type TestimonialControllerUpdateData = {
    body: UpdateTestimonialDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/testimonial/{id}';
};

export type TestimonialControllerUpdateResponses = {
    200: unknown;
};

export type OperationLogControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/operation-log';
};

export type OperationLogControllerFindAllResponses = {
    200: unknown;
};

export type OperationLogControllerCreateData = {
    body: CreateOperationLogDtoWritable;
    path?: never;
    query?: never;
    url: '/api/operation-log';
};

export type OperationLogControllerCreateResponses = {
    201: unknown;
};

export type OperationLogControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/operation-log/{id}';
};

export type OperationLogControllerRemoveResponses = {
    200: unknown;
};

export type OperationLogControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/operation-log/{id}';
};

export type OperationLogControllerFindOneResponses = {
    200: unknown;
};

export type OperationLogControllerUpdateData = {
    body: UpdateOperationLogDtoWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/operation-log/{id}';
};

export type OperationLogControllerUpdateResponses = {
    200: unknown;
};

export type BlogControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/blog';
};

export type BlogControllerFindAllResponses = {
    200: unknown;
};

export type BlogControllerCreateData = {
    body: CreateBlogDtoWritable;
    path?: never;
    query?: never;
    url: '/api/blog';
};

export type BlogControllerCreateResponses = {
    201: unknown;
};

export type BlogControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/blog/{id}';
};

export type BlogControllerRemoveResponses = {
    200: unknown;
};

export type BlogControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/blog/{id}';
};

export type BlogControllerFindOneResponses = {
    200: unknown;
};

export type BlogControllerUpdateData = {
    body: UpdateBlogDtoWritable;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/blog/{id}';
};

export type BlogControllerUpdateResponses = {
    200: unknown;
};
